In [ ]:
import numpy as np

In [ ]:
x= np.array([1,3,4,5,6])
print(x)

In [ ]:
y = np.array([[1,2,3], [2,3,4]])
print(y)

In [ ]:
print('shape:',x.shape)
print('num of dimensions:',x.ndim)
print('type of data:',x.dtype)
print("Y")
print('shape:',y.shape)
print('num of dimensions:',y.ndim)
print('type of data:',y.dtype)

- arange
- linspace
- random.*
- eye
- ones
- zeros

In [ ]:
np.set_printoptions(precision=4, suppress=True)

In [ ]:
a = np.arange(-10, 10, 1.25)
print(a)

In [ ]:
b = np.linspace(0, 1, 100)
print(b)

In [ ]:
np.random.random((3,3)) # random values b/w zero to one

In [ ]:
np.random.randint(1, 1000, (3,3)) # random values b/w start and end

In [ ]:
np.rot90(np.eye(5, dtype=int)) # identity matrix

In [ ]:
np.ones((5,5,), dtype=int)

In [ ]:
np.zeros((5,5), dtype=int)

Operations
- arithmatic
- statistical
- trigonometric
- logical
- slicing
- filtering
- sorting

In [ ]:
x = np.random.randint(1, 25, (2,3))
y = np.random.randint(1, 25, (3,2))
print(x)
print(y)

In [ ]:
y.T

In [ ]:
print("x+y transposed")
print(x + y.T)
print("x transposed + y")
print(x.T + y)

In [ ]:
print("matrix multiplication elementwise")
print(x * y.T)
print("matrix multiplication")
print(x @ y)

In [ ]:
np.hstack((x,x,x,x,x))

In [ ]:
np.vstack((x,x,y.T))

In [ ]:
print(x)
print("sum of all elements:",x.sum())
print("sum of all elements row wise:",x.sum(axis=1))
print("sum of all elements col wise:",x.sum(axis=0))
print("average of all elements :",x.mean())
print("median of all elements :",np.median(x))
print("min of all elements :",x.min())
print("max of all elements :",x.max())
print("std of all elements :",x.std())
print("variance of all elements :",x.var())
print('any item is non-zero:', x.any())
print('all item are non-zero:', x.all())

In [ ]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e) 

In [ ]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

boolean filter

In [ ]:
x[x > 5]

In [ ]:
x = np.random.randint(-3,3, (5,5))
x

In [ ]:
x[(x > -2) & (x < 2)]


#### indexing and slicing

In [ ]:
x

In [ ]:
x[0,0]

syntax for slicing in 1d: `[start:stop:step]`

syntax for slicing in 2d: `[rstart:rstop:rstep, cstart:cstop:cstep]`

In [ ]:
print(x[0]) # first row
print(x[-1]) # last row
print(x[0,:3]) # first row first three elements
print(x[2, -4:]) # 2 index row last four elements
print(x[-1]) # last row

In [ ]:
print(x[:, 0]) # first column
print(x[:, -1]) # last column
print(x[:, :2]) # first two columns
print(x[:, [1, 3]]) # first index and third index column
print(x[:, [2,4]]) # 2,4,1,3 index column

In [118]:
x = np.array([[2,2,1], [6,50,6], [1,7,9]])
x

array([[ 2,  2,  1],
       [ 6, 50,  6],
       [ 1,  7,  9]])

In [109]:
x.sort(axis=1)
x

array([[ 1,  2,  2],
       [ 1,  6,  9],
       [ 6,  7, 50]])

In [115]:
x = x.flatten()
x.sort()

In [116]:
x

array([ 1,  1,  2,  2,  6,  6,  7,  9, 50])

In [119]:
x.max()

50

In [121]:
x.argmax() # returns index of max element

4

In [122]:
x.argmin() # returns index of min element

2