In [ ]:
import numpy as np

In [ ]:
x= np.array([1,3,4,5,6])
print(x)

In [ ]:
y = np.array([[1,2,3], [2,3,4]])
print(y)

In [ ]:
print('shape:',x.shape)
print('num of dimensions:',x.ndim)
print('type of data:',x.dtype)
print("Y")
print('shape:',y.shape)
print('num of dimensions:',y.ndim)
print('type of data:',y.dtype)

- arange
- linspace
- random.*
- eye
- ones
- zeros

In [ ]:
np.set_printoptions(precision=4, suppress=True)

In [ ]:
a = np.arange(-10, 10, 1.25)
print(a)

In [ ]:
b = np.linspace(0, 1, 100)
print(b)

In [ ]:
np.random.random((3,3)) # random values b/w zero to one

In [ ]:
np.random.randint(1, 1000, (3,3)) # random values b/w start and end

In [ ]:
np.rot90(np.eye(5, dtype=int)) # identity matrix

In [ ]:
np.ones((5,5,), dtype=int)

In [ ]:
np.zeros((5,5), dtype=int)

Operations
- arithmatic
- statistical
- trigonometric
- logical
- slicing
- filtering
- sorting

In [ ]:
x = np.random.randint(1, 25, (2,3))
y = np.random.randint(1, 25, (3,2))
print(x)
print(y)

In [ ]:
y.T

In [ ]:
print("x+y transposed")
print(x + y.T)
print("x transposed + y")
print(x.T + y)

In [ ]:
print("matrix multiplication elementwise")
print(x * y.T)
print("matrix multiplication")
print(x @ y)

In [ ]:
np.hstack((x,x,x,x,x))

In [ ]:
np.vstack((x,x,y.T))

In [ ]:
print(x)
print("sum of all elements:",x.sum())
print("sum of all elements row wise:",x.sum(axis=1))
print("sum of all elements col wise:",x.sum(axis=0))
print("average of all elements :",x.mean())
print("median of all elements :",np.median(x))
print("min of all elements :",x.min())
print("max of all elements :",x.max())
print("std of all elements :",x.std())
print("variance of all elements :",x.var())
print('any item is non-zero:', x.any())
print('all item are non-zero:', x.all())

In [ ]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e) 

In [87]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[-0.8462  0.8415  0.4121]
 [-0.2794  0.9129 -0.9614]]
[[-0.5328  0.5403 -0.9111]
 [ 0.9602  0.4081 -0.2752]]
[[ 1.5882  1.5574 -0.4523]
 [-0.291   2.2372  3.4939]]
